//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameClient.rc
//
#define IDR_MAINFRAME                   128
#define IDR_WAVE1                       146
#define IDB_VIEW_FILL                   148
#define IDB_GAME_CARD                   149
#define IDB_JETTOM_VIEW                 150
#define IDB_SCORE_NUMBER                151
#define IDB_BT_JETTON_1000              152
#define IDB_BT_JETTON_10000             153
#define IDB_BT_JETTON_1                 154
#define IDB_BT_JETTON_10                155
#define IDB_BT_JETTON_100               156
#define IDB_BT_JETTON_100000            157
#define IDB_BT_JETTON_50000             158
#define IDB_FRAME_R                     159
#define IDB_FRAME_L                     160
#define IDB_FRAME_M                     161
#define IDB_WIN_FLAGS                   162
#define IDC_SCORE_1                     163
#define IDC_SCORE_10                    164
#define IDC_SCORE_100000                165
#define IDC_SCORE_10000                 166
#define IDC_SCORE_1000                  167
#define IDC_SCORE_100                   168
#define IDR_WAVE2                       174
#define IDD_DLG_GAME_RECORD             177
#define IDB_BT_APPLY_BANKER             179
#define IDB_BITMAP2                     180
#define IDB_BT_CANCEL_BANKER            180
#define IDB_BITMAP1                     183
#define IDC_SCORE_500                   187
#define IDC_SCORE_1000000               187
#define IDC_SCORE_50000                 188
#define IDC_SCORE_5000000               189
#define IDB_BT_SCORE_MOVE_L             190
#define IDB_BT_SCORE_MOVE_R             191
#define IDB_APPLY_USER_BACK             193
#define IDB_FRAME_OLD_PING_JIA          200
#define IDB_FRAME_OLD_TONG_DIAN_PING    201
#define IDB_FRAME_OLD_XIAN_JIA          202
#define IDB_FRAME_OLD_XIAN_TIAN_WANG    203
#define IDB_FRAME_OLD_ZHUANG_JIA        204
#define IDB_FRAME_OLD_ZHUANG_TIAN_WANG  205
#define IDB_GAME_END                    206
#define IDB_CHANGE_BANKER               209
#define IDB_ME_BANKER                   210
#define IDB_NO_BANKER                   211
#define IDB_BT_CANCEL_APPLY             212
#define IDB_TIME_FLAG                   213
#define IDB_ME_SCORE_NUMBER             214
#define IDR_PNG2                        226
#define IDB_BT_JETTON_1000000           227
#define IDB_BT_JETTON_5000000           228
#define IDR_PNG1                        229
#define IDR_PNG3                        230
#define IDB_FRAME_DAO_EMN               231
#define IDB_FRAME_DUI_MEN               232
#define IDB_FRAME_JIAO_L                233
#define IDB_FRAME_JIAO_R                234
#define IDB_FRAME_QIAO                  235
#define IDB_FRAME_SHUN_MEN              236
#define IDB_HAND                        237
#define IDB_BT_JETTON_500000            238
#define IDC_SCORE_500000                239
#define IDB_DISPATCH_CARD               240
#define IDB_BT_AUTO_OPEN_CARD           241
#define IDB_BT_OPEN_CARD                242
#define IDB_BT_CONTINUE_CARD            243
#define IDB_BITMAP3                     244
#define IDB_CONTINUE_CARD               244
#define IDB_FRAME_DAO_EMN_EX            245
#define IDB_FRAME_DUI_MEN_EX            246
#define IDB_FRAME_JIAO_L_EX             247
#define IDB_FRAME_JIAO_R_EX             248
#define IDB_FRAME_QIAO_EX               249
#define IDB_FRAME_SHUN_MEN_EX           250
#define IDB_BITMAP4                     251
#define IDB_BT_BANK                     251
#define IDD_DIALOG1                     253
#define IDD_OPTION                      253
#define IDD_DIALOG2                     254
#define IDD_SELECTDIALOG                254
#define IDD_DIALOG_SYSTEM               255
#define IDB_BT_DRAW                     256
#define IDB_BT_STORAGE                  257
#define IDC_RADIO1                      1000
#define IDC_RADIOSTORE                  1000
#define IDC_RADIO_BEN_40                1000
#define IDC_ALLOWLOOKON                 1001
#define IDC_TEXT_CAPTION                1001
#define IDC_RADIOGET                    1001
#define IDC_RADIO_BAO_30                1001
#define IDC_ENABLE_SOUND                1002
#define IDC_CHECK1                      1002
#define IDC_CHECK_ALL                   1002
#define IDC_RADIO_AO_20                 1002
#define IDC_RADIO_DA_10                 1003
#define IDC_COMBO_TIMES                 1004
#define IDC_RADIO5                      1005
#define IDC_RADIO_BEN_5                 1005
#define IDB_FRAME_TIAN_MEN_EX           1006
#define IDC_RADIO_BAO_5                 1006
#define IDB_FRAME_TIAN_EMN              1007
#define IDC_RADIO_AO_5                  1007
#define IDB_FRAME_DI_MEN_EX             1008
#define IDC_RADIO_DA_5                  1008
#define IDB_FRAME_DI_EMN                1009
#define IDC_BUTTON_RESET                1009
#define IDB_FRAME_XUAN_MEN_EX           1010
#define IDC_BUTTON_SYN                  1010
#define IDB_FRAME_XUAN_EMN              1011
#define IDC_BUTTON_OK                   1011
#define IDB_FRAME_HUANG_MEN_EX          1012
#define IDC_BUTTON_CANCEL               1012
#define IDB_FRAME_HUANG_EMN             1013
#define IDC_STATIC_TIMES                1013
#define IDB_CARDTYPE                    1014
#define IDC_STATIC_AREA                 1014
#define IDB_BT_BT_S                     1015
#define IDC_STATIC_NOTIC                1015
#define IDB_BT_BT_X                     1016
#define IDC_STATIC_TEXT                 1016
#define IDC_STATIC_INFO                 1017
#define IDC_RECORD_LIST                 1056
#define IDC_GAME_GOLD                   6010
#define IDC_STORAGE_GOLD                6011
#define IDC_IN_COUNT                    6014
#define IDC_USER_PASSWORD               6015
#define IDB_BT_JETTON_10000000          6016
#define IDC_SCORE_10000000              6017
#define IDD_BANK_STORAGE                8123
#define STATIC_PASS                     8129
#define IDC_STATIC_PASS                 8129
#define IDB_CENTREBACK                  8130
#define IDB_UNCHECK                     8131
#define IDB_CHECK                       8132
#define BT_APPLY_BANKER_FULL            8181

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
