

#define IDB_BT_JETTON_100                       		"Shark\\BT_JETTON_100.PNG"
#define IDB_BT_JETTON_1000                      		"Shark\\BT_JETTON_1000.PNG"
#define IDB_BT_JETTON_10000                     		"Shark\\BT_JETTON_10000.PNG"
#define IDB_BT_JETTON_100000                    		"Shark\\BT_JETTON_100000.PNG"
#define IDB_BT_JETTON_1000000                   		"Shark\\BT_JETTON_1000000.PNG"
#define IDB_BT_JETTON_10000000                  		"Shark\\BT_JETTON_10000000.PNG"
#define IDB_BT_JETTON									"Shark\\BT_JETTON.PNG"
#define IDB_JETTON_BK									"Shark\\JETTON_BK.PNG"

#define IDB_Image_YanZi									"Shark\\YanZi.PNG"
#define IDB_Image_YanZi1								"Shark\\YanZi1.PNG"
#define IDB_Image_TuZi									"Shark\\TuZi.PNG"
#define IDB_Image_TuZi1									"Shark\\TuZi1.PNG"
#define IDB_Image_GeZi									"Shark\\GeZi.PNG"
#define IDB_Image_GeZi1									"Shark\\GeZi1.PNG"
#define IDB_Image_XiongMao								"Shark\\XiongMao.PNG"
#define IDB_Image_XiongMao1								"Shark\\XiongMao1.PNG"
#define IDB_Image_KongQue								"Shark\\KongQue.PNG"
#define IDB_Image_KongQue1								"Shark\\KongQue1.PNG"
#define IDB_Image_HouZi									"Shark\\HouZi.PNG"
#define IDB_Image_HouZi1								"Shark\\HouZi1.PNG"
#define IDB_Image_LaoYing								"Shark\\LaoYing.PNG"
#define IDB_Image_LaoYing1								"Shark\\LaoYing1.PNG"
#define IDB_Image_ShiZi									"Shark\\ShiZi.PNG"
#define IDB_Image_ShiZi1								"Shark\\ShiZi1.PNG"
#define IDB_Image_DaBaiSha								"Shark\\DaBaiSha.PNG"
#define IDB_Image_DaBaiSha1								"Shark\\DaBaiSha1.PNG"
#define IDB_Image_FeiQin								"Shark\\feiqin.png"
#define IDB_Image_ZouShou								"Shark\\zoushou.PNG"